Python 3.12.5 (tags/v3.12.5:ff3bc82, Aug  6 2024, 20:45:27) [MSC v.1940 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license()" for more information.
>>> 
... from tkinter import *
... from time import *
... 
... def update():
...     time_string = strftime("%I:%M:%S %p")
...     time_label.config(text=time_string)
...     
...     day_string = strftime("%A")
...     day_label.config(text=day_string)
...     
...     date_string = strftime("%B %d, %Y")
...     date_label.config(text=date_string)
... 
...     window.after(1000,update)
... 
... 
... window = Tk()
... 
... time_label = Label(window,font=("Arial",50),fg="#FF0000",bg="black")
... time_label.pack()
... 
... day_label = Label(window,font=("Ink Free",50),fg="#00FF00",bg="black")
... day_label.pack()
... 
... date_label = Label(window,font=("Ink Free",50),fg="#00FF00",bg="black")
... date_label.pack()                   
... 
... update()
... mainloop()
